# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *
from tkinter import messagebox
from PIL import Image, ImageTk
import os
import sys
from Utils.Sources.authen import Auth
# from Utils.Sources.authen import resendEmail

# Explicit imports to satisfy Flake8
# from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage



class UserHandle(Frame):
    def __init__(self, parent):
        super().__init__()
        self.parent = parent
class UserHandle(Frame):
    def __init__(self, parent):
        super().__init__()
        self.parent = parent

        # Create a frame and assigning it to container
        # container = Frame(self)
        # Specify the region where the frame is packed in root
        self.pack(side="top", fill="both", expand=True)
        # Create a frame and assigning it to container
        # container = Frame(self)
        # Specify the region where the frame is packed in root
        self.pack(side="top", fill="both", expand=True)

        # Configure container's location with grid
        self.grid_rowconfigure(0, weight=1)
        self.grid_columnconfigure(0, weight=1)
        # Configure container's location with grid
        self.grid_rowconfigure(0, weight=1)
        self.grid_columnconfigure(0, weight=1)

        # Create a dictionary of frames
        # Create a dictionary of frames
        self.frames = {}
        # we'll create the frames themselves later but let's add the components to the dictionary.
        for F in (login_frame, sign_up_frame,resend):
            frame = F(self, self)

            # the windows class acts as the root window for the frames.
            self.frames[F] = frame
            frame.grid(row=0, column=0, sticky="nsew")

        # Using a method to switch frames
        self.show_frame(login_frame)

    def show_frame(self, cont):
        frame = self.frames[cont]
        # raises the current frame to the top
        frame.tkraise()


class login_frame(Frame):
    def __init__(self, parent, controller):
        self.parent = parent
        self.parent = parent
        Frame.__init__(self, parent)
        self.configure(bg="#FFFFFF")

        scriptdir = os.path.abspath(os.path.dirname(sys.argv[0]))

        def finddir(name, path):
            for root, dirs, files in os.walk(path):
                if name in files:
                    return os.path.join(root, name)

        canvas = Canvas(
            self,
            bg="#FFFFFF",
            height=661,
            width=746,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        canvas.place(x=0, y=0)
        canvas.create_rectangle(
            112.0,
            73.0,
            634.6497802734375,
            614.183349609375,
            fill="#989898",
            outline="")

        txt = Label(self, text="Register here", font=(
            "Lato Regular", 14 * -1), fg="white", bg="#A9A9A9")
        txt.place(x=430, y=393.77)
        txt.bind('<Button-1>', txt_on_click)
        txt.bind('<Enter>', lambda e: txt.configure(fg="#BBBBBB"))
        txt.bind('<Leave>', lambda e: txt.configure(fg="white"))

        # forget pass
        forget_pass = Label(self, text="Forget password?", font=(
            "Lato Regular", 14 * -1), fg="white", bg="#A9A9A9")
        forget_pass.place(x=432, y=288)

        def fgpass_on_click(e):
            forget_pass.configure(fg="#666666")
            controller.show_frame(resend)

        forget_pass.bind('<Button-1>', fgpass_on_click)
        forget_pass.bind(
            '<Enter>', lambda e: forget_pass.configure(fg="#BBBBBB"))
        forget_pass.bind(
            '<Leave>', lambda e: forget_pass.configure(fg="white"))

        canvas.create_text(
            253.0,
            545.0,
            anchor="nw",
            text="Don’t have an account?",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        # create login button
        self.button_image_1 = PhotoImage(
            file=finddir("login_1.png", scriptdir))
        self.button_image_2 = PhotoImage(
            file=finddir("login_1_hover.png", scriptdir))
        self.button_image_3 = PhotoImage(
            file=finddir("login_1_onclick.png", scriptdir))

        def button_1_onclick():
            button_1.configure(image=self.button_image_3)
            # nhảy sang home page tính sau

        button_1 = canvas.create_image(
            273.6806335449219, 480.0,
            anchor='nw',
            image=self.button_image_1
        )
        canvas.tag_bind(button_1, '<ButtonPress-1>', lambda _: self.onLoginClick())

        canvas.create_text(
            221.0,
            198.0,
            anchor="nw",
            text="Username/Email*",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        canvas.create_text(
            223.0,
            298.0,
            anchor="nw",
            text="Password*",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        canvas.create_text(
            328.0,
            94.52175903320312,
            anchor="nw",
            text="LOGIN",
            fill="#FFFFFF",
            font=("Lato Regular", 29 * -1)
        )

        # create textboxes
        self.email = StringVar()
        self.password = StringVar()

        self.entry_image_1 = PhotoImage(file=finddir("entry_1.png", scriptdir))
        entry_bg_1 = canvas.create_image(
            372.6672668457031,
            248.09378051757812,
            image=self.entry_image_1
        )
        entry_1 = Entry(
            self,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0,
            font=("Lato"),
            textvariable=self.email
        )
        entry_1.place(
            x=230.26683902740479,
            y=224.0,
            width=284.8008556365967,
            height=46.18756103515625
        )

        self.entry_image_2 = PhotoImage(file=finddir("entry_2.png", scriptdir))
        entry_bg_2 = canvas.create_image(
            372.8357849121094,
            344.1086120605469,
            image=self.entry_image_2
        )
        entry_2 = Entry(
            self,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0,
            font=('Lato'),
            textvariable=self.password,
            show="•"
        )
        entry_2.place(
            x=230.43535709381104,
            y=320.01483154296875,
            width=284.8008556365967,
            height=46.18756103515625
        )
     
    def onLoginClick(self):
        if (Auth(self.email, self.password).UserAuth()):
            self.parent.parent.Authed.set(True)
            self.parent.parent.geometry('800x480')
            self.parent.parent.main.pack()
            self.parent.destroy()

class sign_up_frame(Frame):
    def __init__(self, parent, controller):
        Frame.__init__(self, parent)
        self.parent = parent
        self.configure(bg="#FFFFFF")

        scriptdir = os.path.abspath(os.path.dirname(sys.argv[0]))

        def finddir(name, path):
            for root, dirs, files in os.walk(path):
                if name in files:
                    return os.path.join(root, name)

        # create canvas
        canvas = Canvas(
            self,
            bg="#FFFFFF",
            height=661,
            width=746,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )

        canvas.place(x=0, y=0)
        canvas.create_rectangle(
            111.81982421875,
            59.925567626953125,
            634.4696044921875,
            601.1089172363281,
            fill="#989898",
            outline="")

        # create Back button
        self.back_img = PhotoImage(file=finddir("back.png", scriptdir))
        self.back_img_hover = PhotoImage(
            file=finddir("back_hover.png", scriptdir))

        back = canvas.create_image(
            138.0,
            2.0,
            anchor="nw",
            image=self.back_img
        )
        canvas.tag_bind(back, '<Button-1>',
                        lambda _: controller.show_frame(login_frame))
        canvas.tag_bind(back, '<Enter>', lambda _: canvas.itemconfigure(
            back, image=self.back_img_hover))
        canvas.tag_bind(back, '<Leave>', lambda _: canvas.itemconfigure(
            back, image=self.back_img))

        # create signup button
        self.button_image_1 = PhotoImage(
            file=r'./UI/assets/frame0/button_1.png')
        self.button_image_2 = PhotoImage(
            file=finddir("button_1_hover.png", scriptdir))
        self.button_image_3 = PhotoImage(
            file=finddir("button_1_onclick.png", scriptdir))

        button_1 = canvas.create_image(
            273.6806640625,
            480.0,
            anchor='nw',
            image=self.button_image_1
        )
        canvas.tag_bind(button_1, '<Button-1>',
                        lambda _: self.onRegisterClick())
        # hover button
        canvas.tag_bind(button_1, '<Enter>', lambda _: canvas.itemconfig(
            button_1, image=self.button_image_2))
        canvas.tag_bind(button_1, '<Leave>', lambda _: canvas.itemconfig(
            button_1, image=self.button_image_1))

        # create texts above textboxes
        canvas.create_text(
            223.0,
            148.0,
            anchor="nw",
            text="Username*",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        canvas.create_text(
            223.0,
            372.0,
            anchor="nw",
            text="Repeat Password*",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        canvas.create_text(
            223.0,
            224.0,
            anchor="nw",
            text="E-mail*",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        canvas.create_text(
            223.0,
            298.0,
            anchor="nw",
            text="Password*",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        canvas.create_text(
            314.4547119140625,
            94.52175903320312,
            anchor="nw",
            text="SIGN UP",
            fill="#FFFFFF",
            font=("Lato Regular", 29 * -1)
        )

        back = canvas.create_text(
            116.81982421875,
            64.925567626953125,
            anchor="nw",
            text="< Back",
            fill="#FFFFFF",
            font=("Lato Regular", 20 * -1)
        )
        canvas.tag_bind(back, '<Button-1>', lambda _: controller.show_frame(login_frame))
        canvas.tag_bind(back, '<Enter>',  lambda _: canvas.itemconfigure(back, fill="#DDDDDD"))
        canvas.tag_bind(back, '<Leave>', lambda _: canvas.itemconfigure(back, fill="white"))


        self.username = StringVar()
        self.Email = StringVar()
        self.password = StringVar()
        self.repeated_pass = StringVar()

        self.entry_image_1 = PhotoImage(file=finddir("entry_1.png", scriptdir))
        entry_bg_1 = canvas.create_image(
            373.6672668457031,
            196.09378051757812,
            image=self.entry_image_1
        )
        entry_1 = Entry(
            self,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0,
            font=("Lato"),
            textvariable=self.username
        )
        entry_1.place(
            x=231.26683902740479,
            y=172.0,
            width=284.8008556365967,
            height=46.18756103515625
        )

        self.entry_image_2 = PhotoImage(file=finddir("entry_2.png", scriptdir))
        entry_bg_2 = canvas.create_image(
            372.8357849121094,
            269.9739227294922,
            image=self.entry_image_2
        )
        entry_2 = Entry(
            self,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0,
            font=("Lato"),
            textvariable=self.Email
        )
        entry_2.place(
            x=230.43535709381104,
            y=245.88014221191406,
            width=284.8008556365967,
            height=46.18756103515625
        )

        self.entry_image_3 = PhotoImage(file=finddir("entry_3.png", scriptdir))
        entry_bg_3 = canvas.create_image(
            372.8357849121094,
            344.1086120605469,
            image=self.entry_image_3
        )
        entry_3 = Entry(
            self,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0,
            font=("Lato"),
            textvariable=self.password,
            show="•"
        )
        entry_3.place(
            x=230.43535709381104,
            y=320.01483154296875,
            width=284.8008556365967,
            height=46.18756103515625
        )

        self.entry_image_4 = PhotoImage(file=finddir("entry_4.png", scriptdir))
        entry_bg_4 = canvas.create_image(
            372.8357849121094,
            418.24334716796875,
            image=self.entry_image_4
        )
        entry_4 = Entry(
            self,
            bd=0,
            bg="#FFFDFD",
            fg="#000716",
            highlightthickness=0,
            font=("Lato"),
            textvariable=self.repeated_pass,
            show="•"
        )
        entry_4.place(
            x=230.43535709381104,
            y=394.1495666503906,
            width=284.8008556365967,
            height=46.18756103515625
        )

    def onRegisterClick(self):
        if (self.password.get() != self.repeated_pass.get()):
            messagebox.showerror('Please retry!',
                                 'Repeated password mismatch!')
            return

        if (Auth(self.Email, self.password,self.username).UserReg()):
            messagebox.showinfo('Register Successfully!',
                                'Please check your email for confirmation!')
            self.parent.show_frame(login_frame)


class resend(Frame):
    def __init__(self, parent, controller):
        Frame.__init__(self, parent)
        self.configure(bg="#FFFFFF")


        scriptdir = os.path.abspath(os.path.dirname(sys.argv[0]))
        #finding files
        def finddir(name, path):
            for root, dirs, files in os.walk(path):
                if name in files:
                    return os.path.join(root, name)
        

        canvas = Canvas(
            self,
            bg="#FFFFFF",
            height=480,
            width=800,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        canvas.place(x=0, y=0)
        canvas.create_rectangle(
            138.0,
            2.0,
            661.0,
            480.0,
            fill="#BAB8B8",
            outline="")

        self.back_img = PhotoImage(file=finddir("back.png", scriptdir))
        self.back_img_hover = PhotoImage(
            file=finddir("back_hover.png", scriptdir))

        back = canvas.create_image(
            138.0,
            2.0,
            anchor="nw",
            image=self.back_img
        )
        canvas.tag_bind(back, '<Button-1>',
                        lambda _: controller.show_frame(login_frame))
        canvas.tag_bind(back, '<Enter>', lambda _: canvas.itemconfigure(
            back, image=self.back_img_hover))
        canvas.tag_bind(back, '<Leave>', lambda _: canvas.itemconfigure(
            back, image=self.back_img))

        self.button_image_2 = PhotoImage(
            file=finddir("button_2.png", scriptdir))
        self.button_image_2_hover = PhotoImage(
            file=finddir("button_2_hover.png", scriptdir))
        button_2 = canvas.create_image(
            309,
            241,
            image=self.button_image_2,
            anchor="nw"
        )
        canvas.tag_bind(button_2, '<ButtonPress-1>',
                        lambda _: self.resend_email_reset())
        canvas.tag_bind(button_2, '<Enter>', lambda _: canvas.itemconfigure(
            button_2, image=self.button_image_2_hover))
        canvas.tag_bind(button_2, '<Leave>', lambda _: canvas.itemconfigure(
            button_2, image=self.button_image_2))

        canvas.create_text(
            248.0,
            146.0,
            anchor="nw",
            text="Send E-mail for resetting password",
            fill="#FFFFFF",
            font=("Lato Regular", 14 * -1)
        )

        self.resend_email = StringVar()
        self.entry_image_1 = PhotoImage(file=finddir("entry_1.png", scriptdir))
        entry_bg_1 = canvas.create_image(
            399.667236328125,
            194.09378051757812,
            image=self.entry_image_1
        )
        entry_1 = Entry(
            self,
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0,
            font=('Lato'),
            textvariable=self.resend_email
        )
        entry_1.place(
            x=257.2668390274048,
            y=170.0,
            width=284.80079460144043,
            height=46.18756103515625
        )
    
    def resend_email_reset(self):
        if (Auth(self.resend_email).Resend()):
            messagebox.showinfo('Send Email Reset Password Successfully!',
                                'Please check your email for confirmation!')
            self.parent.show_frame(login_frame)
        else:
            messagebox.showinfo('Send Email Reset Password Fail!',
                                'Please check email again, email not exist')
            self.parent.show_frame(login_frame)




# if __name__ == "__main__":
#     testObj = UserHandle(self)
#     testObj.mainloop()
